//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/VolumeScenario")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.example.com/VolumeScenario", IsNullable=false)]
public partial class Batch {
    
    private PurchaseOrder[] purchaseOrderField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PurchaseOrder")]
    public PurchaseOrder[] PurchaseOrder {
        get {
            return this.purchaseOrderField;
        }
        set {
            this.purchaseOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/VolumeScenario")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.example.com/VolumeScenario", IsNullable=false)]
public partial class PurchaseOrder {
    
    private string custidField;
    
    private Item[] itemField;
    
    /// <remarks/>
    public string Custid {
        get {
            return this.custidField;
        }
        set {
            this.custidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Item")]
    public Item[] Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.example.com/VolumeScenario")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.example.com/VolumeScenario", IsNullable=false)]
public partial class Item {
    
    private string prodidField;
    
    private double priceField;
    
    private int quantityField;
    
    /// <remarks/>
    public string Prodid {
        get {
            return this.prodidField;
        }
        set {
            this.prodidField = value;
        }
    }
    
    /// <remarks/>
    public double Price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    public int Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
}
