//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.225.
// 
#pragma warning disable 1591

namespace GenPres.GenForm.Products {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProductsSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MobileObject))]
    public partial class Products : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetProductsInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUnitsInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGenericsInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGenericsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetKAEOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetShapesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUnitGroupInfoByUnitOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUnitsByUnitGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUnitGroupsInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRoutesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGenPresDrugDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGenPresPrescriptionUnitsOperationCompleted;
        
        private System.Threading.SendOrPostCallback InvalidateCacheOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Products() {
            this.Url = global::GenPres.Properties.Settings.Default.GenPres_GenForm_Products_Products;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetProductsInfoCompletedEventHandler GetProductsInfoCompleted;
        
        /// <remarks/>
        public event GetUnitsInfoCompletedEventHandler GetUnitsInfoCompleted;
        
        /// <remarks/>
        public event GetGenericsInfoCompletedEventHandler GetGenericsInfoCompleted;
        
        /// <remarks/>
        public event GetGenericsCompletedEventHandler GetGenericsCompleted;
        
        /// <remarks/>
        public event GetKAECompletedEventHandler GetKAECompleted;
        
        /// <remarks/>
        public event GetShapesCompletedEventHandler GetShapesCompleted;
        
        /// <remarks/>
        public event GetUnitGroupInfoByUnitCompletedEventHandler GetUnitGroupInfoByUnitCompleted;
        
        /// <remarks/>
        public event GetUnitsByUnitGroupCompletedEventHandler GetUnitsByUnitGroupCompleted;
        
        /// <remarks/>
        public event GetUnitGroupsInfoCompletedEventHandler GetUnitGroupsInfoCompleted;
        
        /// <remarks/>
        public event GetRoutesCompletedEventHandler GetRoutesCompleted;
        
        /// <remarks/>
        public event GetGenPresDrugDataCompletedEventHandler GetGenPresDrugDataCompleted;
        
        /// <remarks/>
        public event GetGenPresPrescriptionUnitsCompletedEventHandler GetGenPresPrescriptionUnitsCompleted;
        
        /// <remarks/>
        public event InvalidateCacheCompletedEventHandler InvalidateCacheCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProductsInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductInfo[] GetProductsInfo(string filter) {
            object[] results = this.Invoke("GetProductsInfo", new object[] {
                        filter});
            return ((ProductInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProductsInfoAsync(string filter) {
            this.GetProductsInfoAsync(filter, null);
        }
        
        /// <remarks/>
        public void GetProductsInfoAsync(string filter, object userState) {
            if ((this.GetProductsInfoOperationCompleted == null)) {
                this.GetProductsInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductsInfoOperationCompleted);
            }
            this.InvokeAsync("GetProductsInfo", new object[] {
                        filter}, this.GetProductsInfoOperationCompleted, userState);
        }
        
        private void OnGetProductsInfoOperationCompleted(object arg) {
            if ((this.GetProductsInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductsInfoCompleted(this, new GetProductsInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUnitsInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UnitInfo[] GetUnitsInfo(string Name, string Abbreviation, string Group) {
            object[] results = this.Invoke("GetUnitsInfo", new object[] {
                        Name,
                        Abbreviation,
                        Group});
            return ((UnitInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUnitsInfoAsync(string Name, string Abbreviation, string Group) {
            this.GetUnitsInfoAsync(Name, Abbreviation, Group, null);
        }
        
        /// <remarks/>
        public void GetUnitsInfoAsync(string Name, string Abbreviation, string Group, object userState) {
            if ((this.GetUnitsInfoOperationCompleted == null)) {
                this.GetUnitsInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUnitsInfoOperationCompleted);
            }
            this.InvokeAsync("GetUnitsInfo", new object[] {
                        Name,
                        Abbreviation,
                        Group}, this.GetUnitsInfoOperationCompleted, userState);
        }
        
        private void OnGetUnitsInfoOperationCompleted(object arg) {
            if ((this.GetUnitsInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUnitsInfoCompleted(this, new GetUnitsInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGenericsInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GenericInfo[] GetGenericsInfo(string Generic, string Group) {
            object[] results = this.Invoke("GetGenericsInfo", new object[] {
                        Generic,
                        Group});
            return ((GenericInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetGenericsInfoAsync(string Generic, string Group) {
            this.GetGenericsInfoAsync(Generic, Group, null);
        }
        
        /// <remarks/>
        public void GetGenericsInfoAsync(string Generic, string Group, object userState) {
            if ((this.GetGenericsInfoOperationCompleted == null)) {
                this.GetGenericsInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGenericsInfoOperationCompleted);
            }
            this.InvokeAsync("GetGenericsInfo", new object[] {
                        Generic,
                        Group}, this.GetGenericsInfoOperationCompleted, userState);
        }
        
        private void OnGetGenericsInfoOperationCompleted(object arg) {
            if ((this.GetGenericsInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGenericsInfoCompleted(this, new GetGenericsInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGenerics", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetGenerics(string GenericGroup, string UnitGroup, string Shape, string Route) {
            object[] results = this.Invoke("GetGenerics", new object[] {
                        GenericGroup,
                        UnitGroup,
                        Shape,
                        Route});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetGenericsAsync(string GenericGroup, string UnitGroup, string Shape, string Route) {
            this.GetGenericsAsync(GenericGroup, UnitGroup, Shape, Route, null);
        }
        
        /// <remarks/>
        public void GetGenericsAsync(string GenericGroup, string UnitGroup, string Shape, string Route, object userState) {
            if ((this.GetGenericsOperationCompleted == null)) {
                this.GetGenericsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGenericsOperationCompleted);
            }
            this.InvokeAsync("GetGenerics", new object[] {
                        GenericGroup,
                        UnitGroup,
                        Shape,
                        Route}, this.GetGenericsOperationCompleted, userState);
        }
        
        private void OnGetGenericsOperationCompleted(object arg) {
            if ((this.GetGenericsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGenericsCompleted(this, new GetGenericsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetKAE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double GetKAE(string generic, string shape) {
            object[] results = this.Invoke("GetKAE", new object[] {
                        generic,
                        shape});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void GetKAEAsync(string generic, string shape) {
            this.GetKAEAsync(generic, shape, null);
        }
        
        /// <remarks/>
        public void GetKAEAsync(string generic, string shape, object userState) {
            if ((this.GetKAEOperationCompleted == null)) {
                this.GetKAEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKAEOperationCompleted);
            }
            this.InvokeAsync("GetKAE", new object[] {
                        generic,
                        shape}, this.GetKAEOperationCompleted, userState);
        }
        
        private void OnGetKAEOperationCompleted(object arg) {
            if ((this.GetKAECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKAECompleted(this, new GetKAECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetShapes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetShapes(string generic, string unitgroup, string route) {
            object[] results = this.Invoke("GetShapes", new object[] {
                        generic,
                        unitgroup,
                        route});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetShapesAsync(string generic, string unitgroup, string route) {
            this.GetShapesAsync(generic, unitgroup, route, null);
        }
        
        /// <remarks/>
        public void GetShapesAsync(string generic, string unitgroup, string route, object userState) {
            if ((this.GetShapesOperationCompleted == null)) {
                this.GetShapesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShapesOperationCompleted);
            }
            this.InvokeAsync("GetShapes", new object[] {
                        generic,
                        unitgroup,
                        route}, this.GetShapesOperationCompleted, userState);
        }
        
        private void OnGetShapesOperationCompleted(object arg) {
            if ((this.GetShapesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetShapesCompleted(this, new GetShapesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUnitGroupInfoByUnit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UnitGroupInfo GetUnitGroupInfoByUnit(string unit) {
            object[] results = this.Invoke("GetUnitGroupInfoByUnit", new object[] {
                        unit});
            return ((UnitGroupInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetUnitGroupInfoByUnitAsync(string unit) {
            this.GetUnitGroupInfoByUnitAsync(unit, null);
        }
        
        /// <remarks/>
        public void GetUnitGroupInfoByUnitAsync(string unit, object userState) {
            if ((this.GetUnitGroupInfoByUnitOperationCompleted == null)) {
                this.GetUnitGroupInfoByUnitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUnitGroupInfoByUnitOperationCompleted);
            }
            this.InvokeAsync("GetUnitGroupInfoByUnit", new object[] {
                        unit}, this.GetUnitGroupInfoByUnitOperationCompleted, userState);
        }
        
        private void OnGetUnitGroupInfoByUnitOperationCompleted(object arg) {
            if ((this.GetUnitGroupInfoByUnitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUnitGroupInfoByUnitCompleted(this, new GetUnitGroupInfoByUnitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUnitsByUnitGroup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetUnitsByUnitGroup(string unitgroup) {
            object[] results = this.Invoke("GetUnitsByUnitGroup", new object[] {
                        unitgroup});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUnitsByUnitGroupAsync(string unitgroup) {
            this.GetUnitsByUnitGroupAsync(unitgroup, null);
        }
        
        /// <remarks/>
        public void GetUnitsByUnitGroupAsync(string unitgroup, object userState) {
            if ((this.GetUnitsByUnitGroupOperationCompleted == null)) {
                this.GetUnitsByUnitGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUnitsByUnitGroupOperationCompleted);
            }
            this.InvokeAsync("GetUnitsByUnitGroup", new object[] {
                        unitgroup}, this.GetUnitsByUnitGroupOperationCompleted, userState);
        }
        
        private void OnGetUnitsByUnitGroupOperationCompleted(object arg) {
            if ((this.GetUnitsByUnitGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUnitsByUnitGroupCompleted(this, new GetUnitsByUnitGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUnitGroupsInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UnitGroupInfo[] GetUnitGroupsInfo(string generic, string shape, string route) {
            object[] results = this.Invoke("GetUnitGroupsInfo", new object[] {
                        generic,
                        shape,
                        route});
            return ((UnitGroupInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUnitGroupsInfoAsync(string generic, string shape, string route) {
            this.GetUnitGroupsInfoAsync(generic, shape, route, null);
        }
        
        /// <remarks/>
        public void GetUnitGroupsInfoAsync(string generic, string shape, string route, object userState) {
            if ((this.GetUnitGroupsInfoOperationCompleted == null)) {
                this.GetUnitGroupsInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUnitGroupsInfoOperationCompleted);
            }
            this.InvokeAsync("GetUnitGroupsInfo", new object[] {
                        generic,
                        shape,
                        route}, this.GetUnitGroupsInfoOperationCompleted, userState);
        }
        
        private void OnGetUnitGroupsInfoOperationCompleted(object arg) {
            if ((this.GetUnitGroupsInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUnitGroupsInfoCompleted(this, new GetUnitGroupsInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRoutes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetRoutes(string Generic, string Shape, string UnitGroup) {
            object[] results = this.Invoke("GetRoutes", new object[] {
                        Generic,
                        Shape,
                        UnitGroup});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRoutesAsync(string Generic, string Shape, string UnitGroup) {
            this.GetRoutesAsync(Generic, Shape, UnitGroup, null);
        }
        
        /// <remarks/>
        public void GetRoutesAsync(string Generic, string Shape, string UnitGroup, object userState) {
            if ((this.GetRoutesOperationCompleted == null)) {
                this.GetRoutesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRoutesOperationCompleted);
            }
            this.InvokeAsync("GetRoutes", new object[] {
                        Generic,
                        Shape,
                        UnitGroup}, this.GetRoutesOperationCompleted, userState);
        }
        
        private void OnGetRoutesOperationCompleted(object arg) {
            if ((this.GetRoutesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRoutesCompleted(this, new GetRoutesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGenPresDrugData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DrugData GetGenPresDrugData(string Generic, string GenericUnit, string GenericUnitGroup, string Product, string ProductUnit, string ProductUnitGroup, string Shape, string Route) {
            object[] results = this.Invoke("GetGenPresDrugData", new object[] {
                        Generic,
                        GenericUnit,
                        GenericUnitGroup,
                        Product,
                        ProductUnit,
                        ProductUnitGroup,
                        Shape,
                        Route});
            return ((DrugData)(results[0]));
        }
        
        /// <remarks/>
        public void GetGenPresDrugDataAsync(string Generic, string GenericUnit, string GenericUnitGroup, string Product, string ProductUnit, string ProductUnitGroup, string Shape, string Route) {
            this.GetGenPresDrugDataAsync(Generic, GenericUnit, GenericUnitGroup, Product, ProductUnit, ProductUnitGroup, Shape, Route, null);
        }
        
        /// <remarks/>
        public void GetGenPresDrugDataAsync(string Generic, string GenericUnit, string GenericUnitGroup, string Product, string ProductUnit, string ProductUnitGroup, string Shape, string Route, object userState) {
            if ((this.GetGenPresDrugDataOperationCompleted == null)) {
                this.GetGenPresDrugDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGenPresDrugDataOperationCompleted);
            }
            this.InvokeAsync("GetGenPresDrugData", new object[] {
                        Generic,
                        GenericUnit,
                        GenericUnitGroup,
                        Product,
                        ProductUnit,
                        ProductUnitGroup,
                        Shape,
                        Route}, this.GetGenPresDrugDataOperationCompleted, userState);
        }
        
        private void OnGetGenPresDrugDataOperationCompleted(object arg) {
            if ((this.GetGenPresDrugDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGenPresDrugDataCompleted(this, new GetGenPresDrugDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGenPresPrescriptionUnits", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PrescriptionUnits GetGenPresPrescriptionUnits(string GenericUnit, string ProductUnit) {
            object[] results = this.Invoke("GetGenPresPrescriptionUnits", new object[] {
                        GenericUnit,
                        ProductUnit});
            return ((PrescriptionUnits)(results[0]));
        }
        
        /// <remarks/>
        public void GetGenPresPrescriptionUnitsAsync(string GenericUnit, string ProductUnit) {
            this.GetGenPresPrescriptionUnitsAsync(GenericUnit, ProductUnit, null);
        }
        
        /// <remarks/>
        public void GetGenPresPrescriptionUnitsAsync(string GenericUnit, string ProductUnit, object userState) {
            if ((this.GetGenPresPrescriptionUnitsOperationCompleted == null)) {
                this.GetGenPresPrescriptionUnitsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGenPresPrescriptionUnitsOperationCompleted);
            }
            this.InvokeAsync("GetGenPresPrescriptionUnits", new object[] {
                        GenericUnit,
                        ProductUnit}, this.GetGenPresPrescriptionUnitsOperationCompleted, userState);
        }
        
        private void OnGetGenPresPrescriptionUnitsOperationCompleted(object arg) {
            if ((this.GetGenPresPrescriptionUnitsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGenPresPrescriptionUnitsCompleted(this, new GetGenPresPrescriptionUnitsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InvalidateCache", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InvalidateCache() {
            this.Invoke("InvalidateCache", new object[0]);
        }
        
        /// <remarks/>
        public void InvalidateCacheAsync() {
            this.InvalidateCacheAsync(null);
        }
        
        /// <remarks/>
        public void InvalidateCacheAsync(object userState) {
            if ((this.InvalidateCacheOperationCompleted == null)) {
                this.InvalidateCacheOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInvalidateCacheOperationCompleted);
            }
            this.InvokeAsync("InvalidateCache", new object[0], this.InvalidateCacheOperationCompleted, userState);
        }
        
        private void OnInvalidateCacheOperationCompleted(object arg) {
            if ((this.InvalidateCacheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InvalidateCacheCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductInfo : ReadOnlyBaseOfProductInfo {
        
        private int idField;
        
        private string nameField;
        
        private string genericField;
        
        private double genericQuantityField;
        
        private string genericQuantityUnitField;
        
        private string defaultNameField;
        
        private string brandField;
        
        private double quantityField;
        
        private string shapeField;
        
        private float kAEField;
        
        private string packageField;
        
        private string unitField;
        
        private string unitGroupField;
        
        private ProductSubstanceInfo[] substancesField;
        
        private ProductRouteInfo[] routesField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Generic {
            get {
                return this.genericField;
            }
            set {
                this.genericField = value;
            }
        }
        
        /// <remarks/>
        public double GenericQuantity {
            get {
                return this.genericQuantityField;
            }
            set {
                this.genericQuantityField = value;
            }
        }
        
        /// <remarks/>
        public string GenericQuantityUnit {
            get {
                return this.genericQuantityUnitField;
            }
            set {
                this.genericQuantityUnitField = value;
            }
        }
        
        /// <remarks/>
        public string DefaultName {
            get {
                return this.defaultNameField;
            }
            set {
                this.defaultNameField = value;
            }
        }
        
        /// <remarks/>
        public string Brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
            }
        }
        
        /// <remarks/>
        public double Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public string Shape {
            get {
                return this.shapeField;
            }
            set {
                this.shapeField = value;
            }
        }
        
        /// <remarks/>
        public float KAE {
            get {
                return this.kAEField;
            }
            set {
                this.kAEField = value;
            }
        }
        
        /// <remarks/>
        public string Package {
            get {
                return this.packageField;
            }
            set {
                this.packageField = value;
            }
        }
        
        /// <remarks/>
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        public string UnitGroup {
            get {
                return this.unitGroupField;
            }
            set {
                this.unitGroupField = value;
            }
        }
        
        /// <remarks/>
        public ProductSubstanceInfo[] Substances {
            get {
                return this.substancesField;
            }
            set {
                this.substancesField = value;
            }
        }
        
        /// <remarks/>
        public ProductRouteInfo[] Routes {
            get {
                return this.routesField;
            }
            set {
                this.routesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductSubstanceInfo : ReadOnlyBaseOfProductSubstanceInfo {
        
        private int idField;
        
        private int orderField;
        
        private string nameField;
        
        private int substanceIdField;
        
        private double quantityField;
        
        private string unitField;
        
        private int unitIdField;
        
        private double concentrationField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int SubstanceId {
            get {
                return this.substanceIdField;
            }
            set {
                this.substanceIdField = value;
            }
        }
        
        /// <remarks/>
        public double Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        public int UnitId {
            get {
                return this.unitIdField;
            }
            set {
                this.unitIdField = value;
            }
        }
        
        /// <remarks/>
        public double Concentration {
            get {
                return this.concentrationField;
            }
            set {
                this.concentrationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductSubstanceInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ReadOnlyBaseOfProductSubstanceInfo : BindableBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReadOnlyBaseOfUnitGroupInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnitGroupInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReadOnlyBaseOfGenericInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReadOnlyBaseOfUnitInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnitInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReadOnlyBaseOfProductRouteInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductRouteInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReadOnlyBaseOfProductSubstanceInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductSubstanceInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReadOnlyBaseOfProductInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class BindableBase : MobileObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BindableBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReadOnlyBaseOfUnitGroupInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnitGroupInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReadOnlyBaseOfGenericInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReadOnlyBaseOfUnitInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnitInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReadOnlyBaseOfProductRouteInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductRouteInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReadOnlyBaseOfProductSubstanceInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductSubstanceInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReadOnlyBaseOfProductInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class MobileObject {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UnitData {
        
        private string unitField;
        
        private string unitGroupField;
        
        private double multiplierField;
        
        /// <remarks/>
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        public string UnitGroup {
            get {
                return this.unitGroupField;
            }
            set {
                this.unitGroupField = value;
            }
        }
        
        /// <remarks/>
        public double Multiplier {
            get {
                return this.multiplierField;
            }
            set {
                this.multiplierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PrescriptionUnits {
        
        private UnitData[] administerUnitsField;
        
        private UnitData[] doseUnitsField;
        
        /// <remarks/>
        public UnitData[] AdministerUnits {
            get {
                return this.administerUnitsField;
            }
            set {
                this.administerUnitsField = value;
            }
        }
        
        /// <remarks/>
        public UnitData[] DoseUnits {
            get {
                return this.doseUnitsField;
            }
            set {
                this.doseUnitsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DrugData {
        
        private string[] substancesField;
        
        private string[] componentsField;
        
        private string[] concentrationKAEsField;
        
        private string[] substanceUnitsField;
        
        private string[] substanceUnitGroupsField;
        
        private string[] shapesField;
        
        private string[] routesField;
        
        private string[] componentKAEsField;
        
        private string[] componentUnitsField;
        
        private string[] componentUnitGroupsField;
        
        /// <remarks/>
        public string[] Substances {
            get {
                return this.substancesField;
            }
            set {
                this.substancesField = value;
            }
        }
        
        /// <remarks/>
        public string[] Components {
            get {
                return this.componentsField;
            }
            set {
                this.componentsField = value;
            }
        }
        
        /// <remarks/>
        public string[] ConcentrationKAEs {
            get {
                return this.concentrationKAEsField;
            }
            set {
                this.concentrationKAEsField = value;
            }
        }
        
        /// <remarks/>
        public string[] SubstanceUnits {
            get {
                return this.substanceUnitsField;
            }
            set {
                this.substanceUnitsField = value;
            }
        }
        
        /// <remarks/>
        public string[] SubstanceUnitGroups {
            get {
                return this.substanceUnitGroupsField;
            }
            set {
                this.substanceUnitGroupsField = value;
            }
        }
        
        /// <remarks/>
        public string[] Shapes {
            get {
                return this.shapesField;
            }
            set {
                this.shapesField = value;
            }
        }
        
        /// <remarks/>
        public string[] Routes {
            get {
                return this.routesField;
            }
            set {
                this.routesField = value;
            }
        }
        
        /// <remarks/>
        public string[] ComponentKAEs {
            get {
                return this.componentKAEsField;
            }
            set {
                this.componentKAEsField = value;
            }
        }
        
        /// <remarks/>
        public string[] ComponentUnits {
            get {
                return this.componentUnitsField;
            }
            set {
                this.componentUnitsField = value;
            }
        }
        
        /// <remarks/>
        public string[] ComponentUnitGroups {
            get {
                return this.componentUnitGroupsField;
            }
            set {
                this.componentUnitGroupsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnitGroupInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ReadOnlyBaseOfUnitGroupInfo : BindableBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UnitGroupInfo : ReadOnlyBaseOfUnitGroupInfo {
        
        private int idField;
        
        private string nameField;
        
        private UnitInfo[] unitsInfoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public UnitInfo[] UnitsInfo {
            get {
                return this.unitsInfoField;
            }
            set {
                this.unitsInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UnitInfo : ReadOnlyBaseOfUnitInfo {
        
        private int idField;
        
        private string nameField;
        
        private string unitGroupField;
        
        private int unitGroupIdField;
        
        private double multiplierField;
        
        private string abbreviationField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string UnitGroup {
            get {
                return this.unitGroupField;
            }
            set {
                this.unitGroupField = value;
            }
        }
        
        /// <remarks/>
        public int UnitGroupId {
            get {
                return this.unitGroupIdField;
            }
            set {
                this.unitGroupIdField = value;
            }
        }
        
        /// <remarks/>
        public double Multiplier {
            get {
                return this.multiplierField;
            }
            set {
                this.multiplierField = value;
            }
        }
        
        /// <remarks/>
        public string Abbreviation {
            get {
                return this.abbreviationField;
            }
            set {
                this.abbreviationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnitInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ReadOnlyBaseOfUnitInfo : BindableBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GenericInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ReadOnlyBaseOfGenericInfo : BindableBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GenericInfo : ReadOnlyBaseOfGenericInfo {
        
        private int idField;
        
        private string nameField;
        
        private string groupField;
        
        private int groupIdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        public int GroupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductRouteInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ReadOnlyBaseOfProductRouteInfo : BindableBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductRouteInfo : ReadOnlyBaseOfProductRouteInfo {
        
        private int productIdField;
        
        private string productNameField;
        
        private int routeIdField;
        
        private string routeNameField;
        
        /// <remarks/>
        public int ProductId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        public int RouteId {
            get {
                return this.routeIdField;
            }
            set {
                this.routeIdField = value;
            }
        }
        
        /// <remarks/>
        public string RouteName {
            get {
                return this.routeNameField;
            }
            set {
                this.routeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProductInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ReadOnlyBaseOfProductInfo : BindableBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetProductsInfoCompletedEventHandler(object sender, GetProductsInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductsInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductsInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUnitsInfoCompletedEventHandler(object sender, GetUnitsInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUnitsInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUnitsInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UnitInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UnitInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetGenericsInfoCompletedEventHandler(object sender, GetGenericsInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGenericsInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGenericsInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GenericInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GenericInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetGenericsCompletedEventHandler(object sender, GetGenericsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGenericsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGenericsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetKAECompletedEventHandler(object sender, GetKAECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKAECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKAECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetShapesCompletedEventHandler(object sender, GetShapesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetShapesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetShapesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUnitGroupInfoByUnitCompletedEventHandler(object sender, GetUnitGroupInfoByUnitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUnitGroupInfoByUnitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUnitGroupInfoByUnitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UnitGroupInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UnitGroupInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUnitsByUnitGroupCompletedEventHandler(object sender, GetUnitsByUnitGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUnitsByUnitGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUnitsByUnitGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUnitGroupsInfoCompletedEventHandler(object sender, GetUnitGroupsInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUnitGroupsInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUnitGroupsInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UnitGroupInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UnitGroupInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetRoutesCompletedEventHandler(object sender, GetRoutesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRoutesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRoutesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetGenPresDrugDataCompletedEventHandler(object sender, GetGenPresDrugDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGenPresDrugDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGenPresDrugDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DrugData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DrugData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetGenPresPrescriptionUnitsCompletedEventHandler(object sender, GetGenPresPrescriptionUnitsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGenPresPrescriptionUnitsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGenPresPrescriptionUnitsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PrescriptionUnits Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PrescriptionUnits)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InvalidateCacheCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591