<?xml version="1.0" encoding="utf-8"?><Database Class="TestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=C:\Development\GenPres-Development\GenPres\GenPres.DataAccess.Test\TestDatabase.mdf;Integrated Security=True;Connect Timeout=30;User Instance=True" SettingsObjectName="GenPres.DataAccess.Test.Properties.Settings" SettingsPropertyName="TestDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="TestRootTable" Member="TestRootTables">
    <Type Name="TestRootTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
</Database>