//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informedica.GenPres.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Informedica.GenPres.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;logicalunits&gt;
        ///  &lt;logicalunit name=&quot;pediatrie&quot;&gt;
        ///    &lt;patients&gt;
        ///      &lt;lastname&gt;Jan&lt;/lastname&gt;
        ///      &lt;firstname&gt;Janssen&lt;/firstname&gt;
        ///      &lt;hospitalnumber&gt;1234567&lt;/hospitalnumber&gt;
        ///      &lt;length&gt;1.2&lt;/length&gt;
        ///      &lt;weight&gt;12000&lt;/weight&gt;
        ///      &lt;admissiondate&gt;2012/01/01&lt;/admissiondate&gt;
        ///      &lt;unit&gt;2&lt;/unit&gt;
        ///      &lt;bedname&gt;E200&lt;/bedname&gt;
        ///    &lt;/patients&gt;
        ///    &lt;patients&gt;
        ///      &lt;lastname&gt;Piet&lt;/lastname&gt;
        ///      &lt;firstname&gt;Janssen&lt;/firstname&gt;
        ///      &lt;hospitalnumber&gt;1234568&lt;/hospitalnumber&gt;
        ///      &lt;length&gt;0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string patients {
            get {
                return ResourceManager.GetString("patients", resourceCulture);
            }
        }
    }
}
