//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Informedica.GenPres.Data.Visibility {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PrescriptionVisibility {
        
        private PrescriptionVisibilityScenario[] scenarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Scenario")]
        public PrescriptionVisibilityScenario[] Scenario {
            get {
                return this.scenarioField;
            }
            set {
                this.scenarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PrescriptionVisibilityScenario {
        
        private bool genericVisibleField;
        
        private bool genericVisibleFieldSpecified;
        
        private bool routeVisibleField;
        
        private bool routeVisibleFieldSpecified;
        
        private bool shapeVisibleField;
        
        private bool shapeVisibleFieldSpecified;
        
        private bool genericField;
        
        private bool genericFieldSpecified;
        
        private bool routeField;
        
        private bool routeFieldSpecified;
        
        private bool shapeField;
        
        private bool shapeFieldSpecified;
        
        /// <remarks/>
        public bool GenericVisible {
            get {
                return this.genericVisibleField;
            }
            set {
                this.genericVisibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenericVisibleSpecified {
            get {
                return this.genericVisibleFieldSpecified;
            }
            set {
                this.genericVisibleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool RouteVisible {
            get {
                return this.routeVisibleField;
            }
            set {
                this.routeVisibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RouteVisibleSpecified {
            get {
                return this.routeVisibleFieldSpecified;
            }
            set {
                this.routeVisibleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool ShapeVisible {
            get {
                return this.shapeVisibleField;
            }
            set {
                this.shapeVisibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShapeVisibleSpecified {
            get {
                return this.shapeVisibleFieldSpecified;
            }
            set {
                this.shapeVisibleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Generic {
            get {
                return this.genericField;
            }
            set {
                this.genericField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenericSpecified {
            get {
                return this.genericFieldSpecified;
            }
            set {
                this.genericFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Route {
            get {
                return this.routeField;
            }
            set {
                this.routeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RouteSpecified {
            get {
                return this.routeFieldSpecified;
            }
            set {
                this.routeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Shape {
            get {
                return this.shapeField;
            }
            set {
                this.shapeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShapeSpecified {
            get {
                return this.shapeFieldSpecified;
            }
            set {
                this.shapeFieldSpecified = value;
            }
        }
    }
}
